package RMED;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.util.Scanner;

public class Test {
	public static void main(String[]args) throws Exception {
		String var = "		if(RMED_Yr.length() == 0) { RMED_Yr = doctor.RMED_Yr; }\r\n"
				+ "		if(Grad_Year.length() == 0) { Grad_Year = doctor.Grad_Year; }\r\n"
				+ "		if(NPI_Number.length() == 0) { NPI_Number = doctor.NPI_Number; }\r\n"
				+ "		if(Full_Name.length() == 0) { Full_Name = doctor.Full_Name; }\r\n"
				+ "		if(F_Name.length() == 0) { F_Name = doctor.F_Name; }\r\n"
				+ "		if(MI.length() == 0) { MI = doctor.MI; }\r\n"
				+ "		if(L_Name.length() == 0) { L_Name = doctor.L_Name; }\r\n"
				+ "		if(Maid_Name.length() == 0) { Maid_Name = doctor.Maid_Name; }\r\n"
				+ "		if(RMED_Site.length() == 0) { RMED_Site = doctor.RMED_Site; }\r\n"
				+ "		if(Gen.length() == 0) { Gen = doctor.Gen; }\r\n"
				+ "		if(Curr_Email.length() == 0) { Curr_Email = doctor.Curr_Email; }\r\n"
				+ "		if(HomeTown_City.length() == 0) { HomeTown_City = doctor.HomeTown_City; }\r\n"
				+ "		if(HomeTown_State.length() == 0) { HomeTown_State = doctor.HomeTown_State; }\r\n"
				+ "		if(HomeTown_County.length() == 0) { HomeTown_County = doctor.HomeTown_County; }\r\n"
				+ "		if(HomeTown_Rural.length() == 0) { HomeTown_Rural = doctor.HomeTown_Rural; }\r\n"
				+ "		if(HomeTown_RUCA.length() == 0) { HomeTown_RUCA = doctor.HomeTown_RUCA; }\r\n"
				+ "		if(HomeTown_HPSA.length() == 0) { HomeTown_HPSA = doctor.HomeTown_HPSA; }\r\n"
				+ "		if(HomeTown_MUAP.length() == 0) { HomeTown_MUAP = doctor.HomeTown_MUAP; }\r\n"
				+ "		if(HomeTown_At_least_One.length() == 0) { HomeTown_At_least_One = doctor.HomeTown_At_least_One; }\r\n"
				+ "		if(Specialty_Match.length() == 0) { Specialty_Match = doctor.Specialty_Match; }\r\n"
				+ "		if(Residency.length() == 0) { Residency = doctor.Residency; }\r\n"
				+ "		if(Res_City.length() == 0) { Res_City = doctor.Res_City; }\r\n"
				+ "		if(Res_State.length() == 0) { Res_State = doctor.Res_State; }\r\n"
				+ "		if(Res_Zip.length() == 0) { Res_Zip = doctor.Res_Zip; }\r\n"
				+ "		if(Current_Add1.length() == 0) { Current_Add1 = doctor.Current_Add1; }\r\n"
				+ "		if(Curr_City.length() == 0) { Curr_City = doctor.Curr_City; }\r\n"
				+ "		if(Curr_State.length() == 0) { Curr_State = doctor.Curr_State; }\r\n"
				+ "		if(Curr_Zip.length() == 0) { Curr_Zip = doctor.Curr_Zip; }\r\n"
				+ "		if(Curr_County.length() == 0) { Curr_County = doctor.Curr_County; }\r\n"
				+ "		if(Curr_CMS_Rural.length() == 0) { Curr_CMS_Rural = doctor.Curr_CMS_Rural; }\r\n"
				+ "		if(Curr_RUCA.length() == 0) { Curr_RUCA = doctor.Curr_RUCA; }\r\n"
				+ "		if(Curr_PC_HPSA.length() == 0) { Curr_PC_HPSA = doctor.Curr_PC_HPSA; }\r\n"
				+ "		if(Curr_MUAP.length() == 0) { Curr_MUAP = doctor.Curr_MUAP; }\r\n"
				+ "//		if(Curr_At_least_One.length() == 0) { Curr_At_least_One = doctor.Curr_At_least_One; }\r\n"
				+ "		if(Curr_Phone.length() == 0) { Curr_Phone = doctor.Curr_Phone; }\r\n"
				+ "		if(Prac_Name	.length() == 0) { Prac_Name	 = doctor.Prac_Name	; }\r\n"
				+ "		if(Prac_Add1.length() == 0) { Prac_Add1 = doctor.Prac_Add1; }\r\n"
				+ "		if(Prac_Add2.length() == 0) { Prac_Add2 = doctor.Prac_Add2; }\r\n"
				+ "		if(Prac_City.length() == 0) { Prac_City = doctor.Prac_City; }\r\n"
				+ "		if(Prac_State.length() == 0) { Prac_State = doctor.Prac_State; }\r\n"
				+ "		if(Prac_Zip.length() == 0) { Prac_Zip = doctor.Prac_Zip; }\r\n"
				+ "		if(Prac_County.length() == 0) { Prac_County = doctor.Prac_County; }\r\n"
				+ "		if(Prac_CMS_Rural.length() == 0) { Prac_CMS_Rural = doctor.Prac_CMS_Rural; }\r\n"
				+ "		if(Prac_RUCA.length() == 0) { Prac_RUCA = doctor.Prac_RUCA; }\r\n"
				+ "		if(Prac_PC_HPSA.length() == 0) { Prac_PC_HPSA = doctor.Prac_PC_HPSA; }\r\n"
				+ "		if(Prac_PC_MUAP.length() == 0) { Prac_PC_MUAP = doctor.Prac_PC_MUAP; }\r\n"
				+ "//		if(Prac_At_least_One.length() == 0) { Prac_At_least_One = doctor.Prac_At_least_One; }\r\n"
				+ "		if(PR_RMED_SAME.length() == 0) { PR_RMED_SAME = doctor.PR_RMED_SAME; }\r\n"
				+ "		if(PR_RMED.length() == 0) { PR_RMED = doctor.PR_RMED; }\r\n"
				+ "		if(Entity_Type_Code.length() == 0) { Entity_Type_Code = doctor.Entity_Type_Code; }\r\n"
				+ "		if(Replacement_NPI.length() == 0) { Replacement_NPI = doctor.Replacement_NPI; }\r\n"
				+ "		if(Employer_Identification_Number.length() == 0) { Employer_Identification_Number = doctor.Employer_Identification_Number; }\r\n"
				+ "		if(Provider_Organization_Name.length() == 0) { Provider_Organization_Name = doctor.Provider_Organization_Name; }\r\n"
				+ "		if(Provider_Middle_Name.length() == 0) { Provider_Middle_Name = doctor.Provider_Middle_Name; }\r\n"
				+ "		if(Provider_Name_Prefix_Text.length() == 0) { Provider_Name_Prefix_Text = doctor.Provider_Name_Prefix_Text; }\r\n"
				+ "		if(Provider_Name_Suffix_Text.length() == 0) { Provider_Name_Suffix_Text = doctor.Provider_Name_Suffix_Text; }\r\n"
				+ "		if(Provider_Credential_Text.length() == 0) { Provider_Credential_Text = doctor.Provider_Credential_Text; }\r\n"
				+ "		if(Provider_Other_Organization_Name.length() == 0) { Provider_Other_Organization_Name = doctor.Provider_Other_Organization_Name; }\r\n"
				+ "		if(Provider_Other_Organization_Name_Type_Code.length() == 0) { Provider_Other_Organization_Name_Type_Code = doctor.Provider_Other_Organization_Name_Type_Code; }\r\n"
				+ "		if(Provider_First_Line_Business_Mailing_Address.length() == 0) { Provider_First_Line_Business_Mailing_Address = doctor.Provider_First_Line_Business_Mailing_Address; }\r\n"
				+ "		if(Provider_Second_Line_Business_Mailing_Address.length() == 0) { Provider_Second_Line_Business_Mailing_Address = doctor.Provider_Second_Line_Business_Mailing_Address; }\r\n"
				+ "		if(Provider_Business_Mailing_Address_City_Name.length() == 0) { Provider_Business_Mailing_Address_City_Name = doctor.Provider_Business_Mailing_Address_City_Name; }\r\n"
				+ "		if(Provider_Business_Mailing_Address_State_Name.length() == 0) { Provider_Business_Mailing_Address_State_Name = doctor.Provider_Business_Mailing_Address_State_Name; }\r\n"
				+ "		if(Provider_Business_Mailing_Address_Postal_Code.length() == 0) { Provider_Business_Mailing_Address_Postal_Code = doctor.Provider_Business_Mailing_Address_Postal_Code; }\r\n"
				+ "		if(Provider_Business_Mailing_Address_Country_Code.length() == 0) { Provider_Business_Mailing_Address_Country_Code = doctor.Provider_Business_Mailing_Address_Country_Code; }\r\n"
				+ "		if(Provider_Business_Mailing_Address_Telephone_Number.length() == 0) { Provider_Business_Mailing_Address_Telephone_Number = doctor.Provider_Business_Mailing_Address_Telephone_Number; }\r\n"
				+ "		if(Provider_Business_Mailing_Address_Fax_Number.length() == 0) { Provider_Business_Mailing_Address_Fax_Number = doctor.Provider_Business_Mailing_Address_Fax_Number; }\r\n"
				+ "		if(Provider_First_Line_Business_Practice_Location_Address.length() == 0) { Provider_First_Line_Business_Practice_Location_Address = doctor.Provider_First_Line_Business_Practice_Location_Address; }\r\n"
				+ "		if(Provider_Second_Line_Business_Practice_Location_Address.length() == 0) { Provider_Second_Line_Business_Practice_Location_Address = doctor.Provider_Second_Line_Business_Practice_Location_Address; }\r\n"
				+ "		if(Provider_Business_Practice_Location_Address_City_Name.length() == 0) { Provider_Business_Practice_Location_Address_City_Name = doctor.Provider_Business_Practice_Location_Address_City_Name; }\r\n"
				+ "		if(Provider_Business_Practice_Location_Address_State_Name.length() == 0) { Provider_Business_Practice_Location_Address_State_Name = doctor.Provider_Business_Practice_Location_Address_State_Name; }\r\n"
				+ "		if(Provider_Business_Practice_Location_Address_Postal_Code.length() == 0) { Provider_Business_Practice_Location_Address_Postal_Code = doctor.Provider_Business_Practice_Location_Address_Postal_Code; }\r\n"
				+ "		if(Provider_Business_Practice_Location_Address_Country_Code.length() == 0) { Provider_Business_Practice_Location_Address_Country_Code = doctor.Provider_Business_Practice_Location_Address_Country_Code; }\r\n"
				+ "		if(Provider_Business_Practice_Location_Address_Telephone_Number.length() == 0) { Provider_Business_Practice_Location_Address_Telephone_Number = doctor.Provider_Business_Practice_Location_Address_Telephone_Number; }\r\n"
				+ "		if(Provider_Business_Practice_Location_Address_Fax_Number.length() == 0) { Provider_Business_Practice_Location_Address_Fax_Number = doctor.Provider_Business_Practice_Location_Address_Fax_Number; }\r\n"
				+ "		if(Provider_Enumeration_Date.length() == 0) { Provider_Enumeration_Date = doctor.Provider_Enumeration_Date; }\r\n"
				+ "		if(Last_Update_Date.length() == 0) { Last_Update_Date = doctor.Last_Update_Date; }\r\n"
				+ "		if(NPI_Deactivation_Reason_Code.length() == 0) { NPI_Deactivation_Reason_Code = doctor.NPI_Deactivation_Reason_Code; }\r\n"
				+ "		if(NPI_Deactivation_Date.length() == 0) { NPI_Deactivation_Date = doctor.NPI_Deactivation_Date; }\r\n"
				+ "		if(NPI_Reactivation_Date.length() == 0) { NPI_Reactivation_Date = doctor.NPI_Reactivation_Date; }\r\n"
				+ "		if(Authorized_Official_Title_or_Position.length() == 0) { Authorized_Official_Title_or_Position = doctor.Authorized_Official_Title_or_Position; }\r\n"
				+ "		if(Authorized_Official_Telephone_Number.length() == 0) { Authorized_Official_Telephone_Number = doctor.Authorized_Official_Telephone_Number; }\r\n"
				+ "		if(Is_Sole_Proprietor.length() == 0) { Is_Sole_Proprietor = doctor.Is_Sole_Proprietor; }\r\n"
				+ "		if(Is_Organization_Subpart.length() == 0) { Is_Organization_Subpart = doctor.Is_Organization_Subpart; }\r\n"
				+ "		if(Parent_Organization_LBN.length() == 0) { Parent_Organization_LBN = doctor.Parent_Organization_LBN; }\r\n"
				+ "		if(Parent_Organization_TIN.length() == 0) { Parent_Organization_TIN = doctor.Parent_Organization_TIN; }\r\n"
				+ "		if(Certification_Date.length() == 0) { Certification_Date = doctor.Certification_Date; }\r\n";
		Scanner sc = new Scanner(var);
		while(sc.hasNextLine()) {
			String line = sc.nextLine();
			String variable = line.substring(line.indexOf("if(")+3, line.indexOf(".length() == 0"));
			System.out.println("if(" + variable + " == null || " + variable + ".length() == 0) { " + variable + " = doctor." + variable + "; }");
		}
	}
}
